title: Baby Lab Handbook
description: A place for the rules and polices of Baby Lab.
theme: just-the-docs

url: https://mcmaster-baby-lab.github.io/handbook

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
