title: Baby Lab Handbook
description: A place for the rules and polices of Baby Lab.
theme: just-the-docs

url: https://mcmaster-baby-lab.github.io/handbook

aux_links:
  Github Repository: https://github.com/McMaster-Baby-Lab/handbook
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
footer_content: "Copyright &copy; 2020-2023 McMaster Baby Lab.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/McMaster-Baby-Lab/handbook" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-72THWJ89QH
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# customized scheme
color_scheme: babyLab

callouts_level: loud
callouts:
  admonition:
    title: admonition
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: pink
  custom:
    title: Custom
    color: pink
    opacity: 0.3
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: "%b %e %Y at %I:%M %p"